### ISSUE TITLE
Retina image pop-menu 

### ISSUE THREAD

**Issue by nsranga** [SreevishnuAB/RHC#11]
The pop-up should have one more additional image link:
1) Current Vision (and Future Vision)

**Comment by SreevishnuAB** [comment]
Done, sir. Shall I close the issue?

**Comment by SreevishnuAB** [comment]
![screenshot_20181013-190059](https://user-images.githubusercontent.com/35030280/46906046-be15d000-cf1a-11e8-8d9c-f7bf7fbc61ae.png)

**Comment by nsranga** [comment]
Thank you Sree.
