### ISSUE TITLE
Serum cholesterol Validation

### ISSUE THREAD

**Issue by rpraveenpai** [SreevishnuAB/RHC#8]
Min 100
max 400

Code to reflect the above.
Slider  values to reflect it.

**Comment by nsranga** [comment]
thanks praveen for logging this.

i think the upper limit was 300. Was it?

**Comment by SreevishnuAB** [comment]
@nsranga No, sir. 300 was the limit given in the document provided to us. Dr. Gopal then asked us to change the value to 400 during the meeting.

**Comment by nsranga** [comment]
Thank you for the clarification.

**Comment by SreevishnuAB** [comment]
Done
![screenshot_20181013-185946](https://user-images.githubusercontent.com/35030280/46906369-169b9c00-cf20-11e8-85f7-453f72301108.png)
